name: Continuous Deployment

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build JAR
        run: mvn clean install

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: .github/workflows/Dockerfile
          push: true
          tags: |
            thomasjoyce1/tom-taxi-app:latest
            thomasjoyce1/tom-taxi-app:${{ github.sha }}
          build-args: --debug

